#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
IDF_PATH=$(CURDIR)/../esp-idf

PROJECT_NAME := ceytar

include $(IDF_PATH)/make/project.mk

#esp-arduino:
#	mkdir -p components && \
#	cd components && \
#	git clone --recursive https://github.com/espressif/arduino-esp32.git arduino && \

