IDF_PATH=$(CURDIR)/esp-idf

esp-idf:
	git clone -b v3.3.1 --recursive https://github.com/espressif/esp-idf.git

python-setup:
	echo $(IDF_PATH)
	python3 -m pip install --user -r $(IDF_PATH)/requirements.txt





